name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-validate:
    name: Lint & Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --format compact

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
